"""initial resorts table

Revision ID: 0a383566fc09
Revises:
Create Date: 2026-03-28 19:18:05.674772

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a383566fc09"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resorts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("locality", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("has_downhill", sa.Boolean(), nullable=False),
        sa.Column("has_nordic", sa.Boolean(), nullable=False),
        sa.Column("min_elevation", sa.Float(), nullable=True),
        sa.Column("max_elevation", sa.Float(), nullable=True),
        sa.Column("vertical", sa.Float(), nullable=True),
        sa.Column("total_run_length_km", sa.Float(), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("lift_count", sa.Integer(), nullable=False),
        sa.Column("easy_runs", sa.Integer(), nullable=False),
        sa.Column("intermediate_runs", sa.Integer(), nullable=False),
        sa.Column("advanced_runs", sa.Integer(), nullable=False),
        sa.Column("expert_runs", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resorts_lat"), "resorts", ["lat"], unique=False)
    op.create_index(op.f("ix_resorts_lng"), "resorts", ["lng"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resorts_lng"), table_name="resorts")
    op.drop_index(op.f("ix_resorts_lat"), table_name="resorts")
    op.drop_table("resorts")
    # ### end Alembic commands ###
